# Generated by Django 2.0.8 on 2018-10-04 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pycake_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='hyphenated_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pycake_main.Subject'),
        ),
    ]
