# Generated by Django 2.0.8 on 2018-10-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycake_main', '0002_auto_20181004_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='hyphenated_topic',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
