# Generated by Django 2.0.5 on 2018-05-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycake_main', '0003_auto_20180517_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='hyphenated_title',
            field=models.CharField(default='hypnen', max_length=200),
            preserve_default=False,
        ),
    ]
